# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('query_hash', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='hash')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('query_data', picklefield.fields.PickledObjectField(editable=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('date_updated', models.DateTimeField(editable=False, verbose_name='date updated')),
            ],
            options={
                'verbose_name': 'Saved query',
                'verbose_name_plural': 'Saved queries',
            },
        ),
    ]
