# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    replaces = [('django_qbe', '0001_initial'), ('django_qbe', '0002_auto_20161201_1401'), ('django_qbe', '0003_auto_20161228_1409'), ('django_qbe', '0004_auto_20170321_1434')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('report_url', models.TextField(help_text='Enter the absolute url taken from the bookmark button on a report.')),
                ('report_type', models.CharField(choices=[('devices_reporting', 'Beacons'), ('networking_reporting', 'Networking'), ('store_devices_reporting', 'Store Devices')], help_text='Enter the query type that this report will be shown on.', max_length=30)),
            ],
            options={
                'abstract': False,
                'ordering': ('order',),
            },
        ),
    ]
